name: Makefile CI

on:
  push:
    branches: [ pr-github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: configure
    #   run: ./configure

    - name: Install dependencies
      run: make install

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
